global using judo_univ_rennes.Configurations;
global using judo_univ_rennes.Contracts;
global using judo_univ_rennes.Data;
global using judo_univ_rennes.Data.TableInfos;
global using judo_univ_rennes.Dtos;
global using judo_univ_rennes.Dtos.User;
global using judo_univ_rennes.Dtos.Auth;
global using judo_univ_rennes.Dtos.Commands;
global using judo_univ_rennes.Dtos.Comments;
global using judo_univ_rennes.Dtos.Notifications;
global using judo_univ_rennes.Dtos.IndexMarkdowns;
global using judo_univ_rennes.Dtos.Newss;
global using judo_univ_rennes.Dtos.Posts;
global using judo_univ_rennes.Provider;
global using judo_univ_rennes.Services;
global using judo_univ_rennes.RequestFeatures;
global using judo_univ_rennes.Hubs;
global using judo_univ_rennes.MailHelper;
global using judo_univ_rennes.Static;
global using judo_univ_rennes.Statics;
global using AutoMapper;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.SignalR.Client;

//global using Microsoft.AspNetCore.Mvc;
global using System.Configuration;
global using System.Security.Claims;
global using System.IdentityModel.Tokens.Jwt;
global using System.Text;
global using System.ComponentModel.DataAnnotations.Schema;
global using Autofac.Core;
global using Serilog;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Options;
global using MongoDB.Driver;
global using Blazored.LocalStorage;
global using Blazored.Video;
global using BlazorPro.Spinkit;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.Extensions.Caching.Memory;
global using Blazorise;
global using Blazorise.Bootstrap;

global using Google;
global using Npgsql;
global using Blazorise.Icons.FontAwesome;
global using judo_univ_rennes.StartUps;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.StaticFiles;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
global using MudBlazor;
global using MudBlazor.Services;
global using Tewr.Blazor.FileReader;
global using Prometheus;
global using Blazorise.RichTextEdit;
global using Microsoft.AspNetCore.ResponseCompression;
global using Microsoft.AspNetCore.SignalR;
global using Newtonsoft.Json;
global using System.Data;

global using MailKit.Net.Smtp;
global using MimeKit;


global using Color = MudBlazor.Color;
global using Size = MudBlazor.Size;
global using Margin = MudBlazor.Margin;
global using ButtonType = MudBlazor.ButtonType;
